# override your production parameters
# $ jekyll serve --config _config.yml,_config_dev.yml 

url: "http://localhost:4000" 

# External Services, leave blank to ignore or put true to use
service:
  google_analytics_key: false
  yandex_metrica_key: false
  disqus_key: false  
  muut: false
  google_adsense: false
   
comments: false



