# override your production parameters
# $ jekyll serve --config _config.yml,_config_dev.yml 

# Server
# port: 4001

# access from mobile
# host: 0.0.0.0

url: "http://localhost:4000"
baseurl: "" 

# External Services, leave blank to ignore or put true to use
service:
  google_analytics_key: false
  yandex_metrica_key: false
  disqus_key: false  
  muut: false
 google_adsense: false
   
comments: false
